# Generated by Django 4.1.4 on 2024-12-20 06:19

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=contact.models.generate_unique_filename
            ),
        ),
    ]
